<a href="https://colab.research.google.com/github/tahsinulhq/NN_assignments/blob/main/assign1_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
import torchvision.datasets as datasets
import numpy as np

In [2]:
cifar_trainset = datasets.CIFAR10(root='./data', train=True, download=True, transform=None)
cifar_testset = datasets.CIFAR10(root='./data', train=False, download=True, transform=None)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [3]:
X_train = cifar_trainset.data
X_test = cifar_testset.data

In [4]:
Y_train = cifar_trainset.targets
Y_test = cifar_testset.targets

In [5]:
labels = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [6]:
Xtr_rows = X_train.reshape(X_train.shape[0], 32 * 32 * 3)
Xte_rows = X_test.reshape(X_test.shape[0], 32 * 32 * 3)

In [1]:
import numpy as np

class NearestNeighbor(object):
  def __init__(self):
    pass

  def train(self, X, y):
    """ X is N x D where each row is an example. Y is 1-dimension of size N """
    # the nearest neighbor classifier simply remembers all the training data
    self.Xtrain = X
    self.ytrain = y

  def predict(self, X):
    """ X is N x D where each row is an example we wish to predict label for """
    num_test = X.shape[0]
    # lets make sure that the output type matches the input type
    Ypred = np.zeros(num_test)

    # loop over all test rows
    for i in range(num_test):
      # find the nearest training image to the i'th test image
      # using the L1 distance (sum of absolute value differences)
      distances = np.sum(np.abs(self.Xtrain - X[i,:]), axis = 1)
      min_index = np.argmin(distances) # get the index with smallest distance
      Ypred[i] = self.ytrain[min_index] # predict the label of the nearest example

    return Ypred

In [8]:
nn = NearestNeighbor()
nn.train(Xtr_rows, Y_train)
Xte_rows = np.array(Xte_rows)

a = nn.predict(Xte_rows)
print((np.mean(a == Y_test) ))

0.2492


In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, a))
print(classification_report(Y_test, a))

[[524  24 155  24  31  18  42  12 161   9]
 [189 126  99  68  81  71  53  30 236  47]
 [233   2 313  88 140  65  52  20  76  11]
 [196  17 161 171 106 146  86  28  80   9]
 [178   6 259  66 246  80  51  16  94   4]
 [195   7 138 149  82 242  60  37  82   8]
 [114   3 233 114 154 124 165  10  78   5]
 [190  16 167  99 160  65  65 133  88  17]
 [273  45  64  32  36  27  17  16 481   9]
 [219  89  76  64  60  74  53  42 232  91]]
              precision    recall  f1-score   support

           0       0.23      0.52      0.32      1000
           1       0.38      0.13      0.19      1000
           2       0.19      0.31      0.23      1000
           3       0.20      0.17      0.18      1000
           4       0.22      0.25      0.23      1000
           5       0.27      0.24      0.25      1000
           6       0.26      0.17      0.20      1000
           7       0.39      0.13      0.20      1000
           8       0.30      0.48      0.37      1000
           9       0.43     