<a href="https://colab.research.google.com/github/tahsinulhq/NN_assignments/blob/main/k3%2C5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision
import torchvision.datasets as datasets
import numpy as np

In [2]:
cifar_trainset = datasets.CIFAR10(root='./data', train=True, download=True, transform=None)
cifar_testset = datasets.CIFAR10(root='./data', train=False, download=True, transform=None)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [3]:
X_train = cifar_trainset.data
X_test = cifar_testset.data

In [4]:
Y_train = np.array(cifar_trainset.targets)
Y_test = np.array(cifar_testset.targets)

In [5]:
labels = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [6]:
Xtr_rows = X_train.reshape(X_train.shape[0], 32 * 32 * 3)
Xte_rows = X_test.reshape(X_test.shape[0], 32 * 32 * 3)

In [23]:
import numpy as np

class KNearestNeighbor(object):
  def __init__(self):
    pass

  def train(self, X, y):
    """ X is N x D where each row is an example. Y is 1-dimension of size N """
    # the nearest neighbor classifier simply remembers all the training data
    self.Xtrain = X
    self.ytrain = y

  def distances(self, X):
     num_test = X.shape[0]
     num_train = self.X_train.shape[0]
     dists = np.zeros((num_test, num_train))
     for i in range(num_test):
       dists[i] = np.sqrt(np.sum(np.square(X[i] - self.Xtrain), axis = 1))
       

     return dists

  def predict(self,  dists, k=3):
    
    num_test = dists.shape[0]
    # lets make sure that the output type matches the input type
    Ypred = np.zeros(num_test)

    # loop over all test rows
    for i in range(num_test):
      closest_y = []
      sorted_dist = np.argsort(dists[i])
      closest_y = list(self.ytrain[sorted_dist[0:k]])
      #closest_y = self.ytrain[np.argsort(dists[i])][:k]
      Ypred[i] = np.argmax(np.bincount(closest_y))

    return Ypred

In [24]:
knn = KNearestNeighbor()
knn.train(Xtr_rows, Y_train)
#Xte_rows = np.array(Xte_rows)

a = knn.predict(Xte_rows, k=3)
print((np.mean(a == Y_test) ))

0.0969


In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, a))
print(classification_report(Y_test, a))

[[241 177 179 114  98  58  39  31  37  26]
 [252 166 201 114  83  57  45  28  29  25]
 [236 195 164 126  88  71  47  29  21  23]
 [271 190 146 111  75  55  49  33  29  41]
 [252 193 147 113  90  61  48  33  32  31]
 [257 202 157 108  84  58  54  36  22  22]
 [244 200 139 137  93  66  47  25  24  25]
 [251 211 150 126  81  55  32  39  27  28]
 [232 176 191 104  89  67  46  37  36  22]
 [245 168 183 124 101  60  38  38  26  17]]
              precision    recall  f1-score   support

           0       0.10      0.24      0.14      1000
           1       0.09      0.17      0.12      1000
           2       0.10      0.16      0.12      1000
           3       0.09      0.11      0.10      1000
           4       0.10      0.09      0.10      1000
           5       0.10      0.06      0.07      1000
           6       0.11      0.05      0.07      1000
           7       0.12      0.04      0.06      1000
           8       0.13      0.04      0.06      1000
           9       0.07     